### PR TITLE
Add support for count and isEmpty as set functions in queries. Fixes …

### PR DESCRIPTION
**Pull request by plorenz**
…GH-7

### CODE REVIEW

**Comment by dovholuknf** [comment]
Is there any usage information on how to regenerate this stuff? I looked at/skimmed storage/ast/README.md but i didn't see anything about the how to regen/update listed in there. i'm not well versed in ANTLR is this all "obvious" if one knows ANTLR or is there some doc that you could add to aid the next round of people who end up looking at this code?

**Comment by plorenz** [comment]
> Is there any usage information on how to regenerate this stuff? I looked at/skimmed storage/ast/README.md but i didn't see anything about the how to regen/update listed in there. i'm not well versed in ANTLR is this all "obvious" if one knows ANTLR or is there some doc that you could add to aid the next round of people who end up looking at this code?

There's a `generate.sh` next to the antlr file. I could add a README that says run generate.sh :)

**Comment by dovholuknf** [comment]
> There's a `generate.sh` next to the antlr file. I could add a README that says run generate.sh :)

honestly it might sound dumb but it's probably helpful to do that.

**Comment by plorenz** [comment]
> > There's a `generate.sh` next to the antlr file. I could add a README that says run generate.sh :)
> 
> honestly it might sound dumb but it's probably helpful to do that.

Added a README.md for the storage library as a whole, including a link to `generate.sh`

**Pull request merged**
